# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Angular app to Azure Web App - tabverse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./menu-app
        run: npm ci

      - name: Build Angular app
        working-directory: ./menu-app
        run: npx ng build --configuration=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: menu-app/dist/menu-app/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8310048816E34B6BA826AF29E8540B56 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_372D5F842AE045719DEF209D46BC1CDA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6EC3D2BBB524DE68D5C0D50AB7B42D5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tabverse'
          slot-name: 'Production'
          package: .
